services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "98481TesteServer!"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserverdata:/var/opt/mssql
volumes:
  sqlserverdata:
